//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Windows.Controls.CommonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/PACT.Service")]
    [System.SerializableAttribute()]
    public partial class SearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMoveUpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTagWiseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaximumRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrimaryValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectedValueQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhereStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((this.CustomerNoField.Equals(value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupBy {
            get {
                return this.GroupByField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupByField, value) != true)) {
                    this.GroupByField = value;
                    this.RaisePropertyChanged("GroupBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMoveUp {
            get {
                return this.IsMoveUpField;
            }
            set {
                if ((this.IsMoveUpField.Equals(value) != true)) {
                    this.IsMoveUpField = value;
                    this.RaisePropertyChanged("IsMoveUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTagWise {
            get {
                return this.IsTagWiseField;
            }
            set {
                if ((this.IsTagWiseField.Equals(value) != true)) {
                    this.IsTagWiseField = value;
                    this.RaisePropertyChanged("IsTagWise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Location {
            get {
                return this.LocationField;
            }
            set {
                if ((this.LocationField.Equals(value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumRows {
            get {
                return this.MaximumRowsField;
            }
            set {
                if ((this.MaximumRowsField.Equals(value) != true)) {
                    this.MaximumRowsField = value;
                    this.RaisePropertyChanged("MaximumRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryKey {
            get {
                return this.PrimaryKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryKeyField, value) != true)) {
                    this.PrimaryKeyField = value;
                    this.RaisePropertyChanged("PrimaryKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrimaryValue {
            get {
                return this.PrimaryValueField;
            }
            set {
                if ((this.PrimaryValueField.Equals(value) != true)) {
                    this.PrimaryValueField = value;
                    this.RaisePropertyChanged("PrimaryValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductNo {
            get {
                return this.ProductNoField;
            }
            set {
                if ((this.ProductNoField.Equals(value) != true)) {
                    this.ProductNoField = value;
                    this.RaisePropertyChanged("ProductNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchOn {
            get {
                return this.SearchOnField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchOnField, value) != true)) {
                    this.SearchOnField = value;
                    this.RaisePropertyChanged("SearchOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchValue {
            get {
                return this.SearchValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchValueField, value) != true)) {
                    this.SearchValueField = value;
                    this.RaisePropertyChanged("SearchValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedValueQuery {
            get {
                return this.SelectedValueQueryField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedValueQueryField, value) != true)) {
                    this.SelectedValueQueryField = value;
                    this.RaisePropertyChanged("SelectedValueQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhereString {
            get {
                return this.WhereStringField;
            }
            set {
                if ((object.ReferenceEquals(this.WhereStringField, value) != true)) {
                    this.WhereStringField = value;
                    this.RaisePropertyChanged("WhereString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonService.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetCommonData", ReplyAction="http://tempuri.org/ICommon/GetCommonDataResponse")]
        string GetCommonData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetScreenInfoByID", ReplyAction="http://tempuri.org/ICommon/GetScreenInfoByIDResponse")]
        System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/ExecuteQuery", ReplyAction="http://tempuri.org/ICommon/ExecuteQueryResponse")]
        System.Data.DataTable ExecuteQuery(string Query, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CreateAccount", ReplyAction="http://tempuri.org/ICommon/CreateAccountResponse")]
        int CreateAccount(string XMLControlData, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CreateProduct", ReplyAction="http://tempuri.org/ICommon/CreateProductResponse")]
        int CreateProduct(string XMLControlData, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataTable_Search", ReplyAction="http://tempuri.org/ICommon/GetDataTable_SearchResponse")]
        System.Data.DataTable GetDataTable_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataTable", ReplyAction="http://tempuri.org/ICommon/GetDataTableResponse")]
        System.Data.DataTable GetDataTable(string strQuery, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataSet_Search", ReplyAction="http://tempuri.org/ICommon/GetDataSet_SearchResponse")]
        System.Data.DataSet GetDataSet_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : Microsoft.Windows.Controls.CommonService.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<Microsoft.Windows.Controls.CommonService.ICommon>, Microsoft.Windows.Controls.CommonService.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCommonData(int value) {
            return base.Channel.GetCommonData(value);
        }
        
        public System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex) {
            return base.Channel.GetScreenInfoByID(ScreenID, CompanyIndex);
        }
        
        public System.Data.DataTable ExecuteQuery(string Query, string CompanyIndex) {
            return base.Channel.ExecuteQuery(Query, CompanyIndex);
        }
        
        public int CreateAccount(string XMLControlData, string CompanyIndex) {
            return base.Channel.CreateAccount(XMLControlData, CompanyIndex);
        }
        
        public int CreateProduct(string XMLControlData, string CompanyIndex) {
            return base.Channel.CreateProduct(XMLControlData, CompanyIndex);
        }
        
        public System.Data.DataTable GetDataTable_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex) {
            return base.Channel.GetDataTable_Search(objSearch, CompanyIndex);
        }
        
        public System.Data.DataTable GetDataTable(string strQuery, string CompanyIndex) {
            return base.Channel.GetDataTable(strQuery, CompanyIndex);
        }
        
        public System.Data.DataSet GetDataSet_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex) {
            return base.Channel.GetDataSet_Search(objSearch, CompanyIndex);
        }
    }
}
