//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACT.MODEL.CommonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonService.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetCommonData", ReplyAction="http://tempuri.org/ICommon/GetCommonDataResponse")]
        string GetCommonData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetScreenInfoByID", ReplyAction="http://tempuri.org/ICommon/GetScreenInfoByIDResponse")]
        System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : PACT.MODEL.CommonService.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<PACT.MODEL.CommonService.ICommon>, PACT.MODEL.CommonService.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCommonData(int value) {
            return base.Channel.GetCommonData(value);
        }
        
        public System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex) {
            return base.Channel.GetScreenInfoByID(ScreenID, CompanyIndex);
        }
    }
}
