namespace Microsoft.Windows.Controls
{
    using System;
    using System.IO;
    using System.Text;
    using System.Collections;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    using System.Data;
    using System.ComponentModel;
    
    using System.Runtime.Serialization.Formatters.Binary;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Director", "0.0.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]

    public partial class TreeColumn
    {
        
        //private string _Allignment;
        //[TypeConverter(typeof(Allignfields))]
        //public string Allignment
        //{
        //    get { return _Allignment; }
        //    set { _Allignment = value; }
        //}
        
        
       
        private string _Name;
        /// <summary>
        /// Sets or gets the <see cref="_Name" />
        /// value of the <see cref="TreeColumn" />
        /// object class.
        /// </summary>
        
       
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }
        

        private string _Label;
        /// <summary>
        /// Sets or gets the <see cref="_Label" />
        /// value of the <see cref="TreeColumn" />
        /// object class.
        /// </summary>
        public string Label
        {
            get { return _Label; }
            set { _Label = value; }
        }

        private int _Width;
        /// <summary>
        /// Sets or gets the <see cref="_Width" />
        /// value of the <see cref="TreeColumn" />
        /// object class.
        /// </summary>
        public int Width
        {
            get { return _Width; }
            set { _Width = value; }
        }

        private string _Filtercol;
        [System.ComponentModel.Browsable(false)]
        public string  Filtercol
        {
            get { return _Filtercol; }
            set { _Filtercol = value; }
        }

        private bool _HideField;
        [System.ComponentModel.Browsable(false)]
        public bool HideField
        {
            get { return _HideField; }
            set { _HideField = value; }
        }

        private short _Decimals;
        public short Decimals
        {
            get { return _Decimals; }
            set { _Decimals = value; }
        }

        

        /// <summary>
        /// Gets the XML string for the serialized
        /// <see cref="PACTRequest" /> object.
        /// </summary>
        [System.ComponentModel.Browsable(false)]
        public virtual string Xml
        {
            get
            {
                return PACTSerializer.ToXml(this, this.GetType(), false);
            }
        }

        /// <summary>
        /// Creates a new <see cref="PACTRequest" /> 
        /// object from an XML string.
        /// </summary>
        /// <param name="Xml">
        /// XML string to create the object from.</param>
        /// <returns>
        /// A <see cref="PACTRequest" /> object.
        /// </returns>
        public static TreeColumn FromXml(string Xml)
        {
            return ((TreeColumn)(PACTSerializer.FromXml(Xml, typeof(TreeColumn))));
        }
        /// <summary>
        /// Gets the schema location as a URI string.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The location is generated from the source location
        /// specified for the schema.
        /// </para>
        /// <para>
        /// Note that this property must be generated with a set accessor in order
        /// that the <b>xsi:schemaLocation</b> attribute is correctly generated by
        /// the <see cref="XmlSerializer" /> object.
        /// </para>
        /// </remarks>
        //[System.Xml.Serialization.XmlAttributeAttribute(Namespace = "http://www.w3.org/2001/XMLSchema-instance")]
        //[System.ComponentModel.Browsable(false)]
        //public virtual string noNamespaceSchemaLocation
        //{
        //    get
        //    {
        //        return "TreeColumn.xsd";
        //    }
        //    set
        //    {
        //    }
        //}

    }//Class
}//Namespace
