update AdmnLayoutScreens set ScreenXML='<?xml version="1.0" encoding="utf-8" ?>
<ScreenXML  TableName="Accounts" PrimaryColumn="NodeNo" ExtendedPrimaryColumn="">
  <Section Name="" Type="Static">
    <Tab Name="" TabType="Panel">
      <Row>
        <Field>
          <ID>txtCode</ID>
          <Name>txtCode</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Code</Label>
          <IsMandatory>1</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>INT</DataType>
          <Db>Code</Db>
        </Field>
        <Field>
          <ID>drpAccountType</ID>
          <Name>drpAccountType</Name>
          <FType>Static</FType>
          <Control>ComboBox</Control>
          <Label>Type</Label>
          <IsMandatory>1</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>INT</DataType>
          <Db>Type1</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtName</ID>
          <Name>txtName</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Name</Label>
          <IsMandatory>1</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Name</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtAliasName</ID>
          <Name>txtAliasName</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Alias Name</Label>
          <IsMandatory>1</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Alias</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtGroup</ID>
          <Name>txtGroup</Name>
          <FType>Static</FType>
          <Control>ComboBox</Control>
          <Label>Group</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Group1</Db>
        </Field>
        <Field>
          <ID>drpAccountStatus</ID>
          <Name>drpAccountStatus</Name>
          <FType>Static</FType>
          <Control>ComboBox</Control>
          <Label>Status</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>INT</DataType>
          <Db>Status</Db>
        </Field>
      </Row>
    </Tab>
  </Section>
  <Section Name="" Type="Extra">
    <Tab Name="Master" TabType="Tab">
      <Row>
        <Field>
          <ID>txtAddress1</ID>
          <Name>txtAddress1</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Address1</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Address1</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtAddress2</ID>
          <Name>txtAddress2</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Address2</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Address2</Db>
        </Field>
        <Field>
          <ID>txtAddress3</ID>
          <Name>txtAddress3</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Address3</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Address3</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtFaxNo</ID>
          <Name>txtFax</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Fax No</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Faxno</Db>
        </Field>
        <Field>
          <ID>txtContactPerson</ID>
          <Name>txtContactPerson</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Contact Person</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>ContactPerson</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtEmail</ID>
          <Name>txtEmail</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Email</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>Email</Db>
        </Field>
        <Field>
          <ID>txtPhoneNo</ID>
          <Name>txtPhoneNo</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Phone No</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>PhoneNo</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtCreditLimit</ID>
          <Name>txtCreditLimit</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>CreditLimit</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>CreditLimit</Db>
        </Field>
        <Field>
          <ID>txtDebitLimit</ID>
          <Name>txtDebitLimit</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>DebitLimit</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>DebitLimit</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>txtCreditDays</ID>
          <Name>txtCreditDays</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Credit Days</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>CreditDays</Db>
        </Field>
        <Field>
          <ID>txtDebitDays</ID>
          <Name>txtDebitDays</Name>
          <FType>Static</FType>
          <Control>TextBox</Control>
          <Label>Debit Days</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>DebitDays</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>drpSalesAccount</ID>
          <Name>drpSalesAccount</Name>
          <FType>Static</FType>
          <Control>ListDrop</Control>
          <Label>Sales Account</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>SalesAccount</Db>
        </Field>
        <Field>
          <ID>drpPurchaseAccount</ID>
          <Name>drpPurchaseAccount</Name>
          <FType>Static</FType>
          <Control>ComboBox</Control>
          <Label>Purchase Account</Label>
          <IsMandatory>0</IsMandatory>
          <IsReadOnly>0</IsReadOnly>
          <DataType>TEXT</DataType>
          <Db>PurchaseAccount</Db>
        </Field>
      </Row>
      <Row>
        <Field>
          <ID>SaveButton</ID>
          <Name>SaveButton</Name>
          <FType>Static</FType>
          <Control>Button</Control>
          <Label>Save</Label>
		 <Command>AccountCreate</Command>
          <IsMandatory>1</IsMandatory>
          <IsReadOnly>1</IsReadOnly>
          <DataType></DataType>
          <Db>SaveAccount</Db>
        </Field>
       
      </Row>
    </Tab>
  </Section>
</ScreenXML>'
Where FeatureID=1000