//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACT.COMMON.CommonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonService.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetCommonData", ReplyAction="http://tempuri.org/ICommon/GetCommonDataResponse")]
        string GetCommonData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetScreenInfoByID", ReplyAction="http://tempuri.org/ICommon/GetScreenInfoByIDResponse")]
        System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/ExecuteQuery", ReplyAction="http://tempuri.org/ICommon/ExecuteQueryResponse")]
        System.Data.DataTable ExecuteQuery(string Query, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CreateAccount", ReplyAction="http://tempuri.org/ICommon/CreateAccountResponse")]
        int CreateAccount(string XMLControlData, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CreateDepreciation", ReplyAction="http://tempuri.org/ICommon/CreateDepreciationResponse")]
        int CreateDepreciation(string XMLControlData, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CreateProduct", ReplyAction="http://tempuri.org/ICommon/CreateProductResponse")]
        int CreateProduct(string XMLControlData, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataTable_Search", ReplyAction="http://tempuri.org/ICommon/GetDataTable_SearchResponse")]
        System.Data.DataTable GetDataTable_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataTable", ReplyAction="http://tempuri.org/ICommon/GetDataTableResponse")]
        System.Data.DataTable GetDataTable(string strQuery, string CompanyIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetDataSet_Search", ReplyAction="http://tempuri.org/ICommon/GetDataSet_SearchResponse")]
        System.Data.DataSet GetDataSet_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : PACT.COMMON.CommonService.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<PACT.COMMON.CommonService.ICommon>, PACT.COMMON.CommonService.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCommonData(int value) {
            return base.Channel.GetCommonData(value);
        }
        
        public System.Data.DataSet GetScreenInfoByID(int ScreenID, string CompanyIndex) {
            return base.Channel.GetScreenInfoByID(ScreenID, CompanyIndex);
        }
        
        public System.Data.DataTable ExecuteQuery(string Query, string CompanyIndex) {
            return base.Channel.ExecuteQuery(Query, CompanyIndex);
        }
        
        public int CreateAccount(string XMLControlData, string CompanyIndex) {
            return base.Channel.CreateAccount(XMLControlData, CompanyIndex);
        }
        
        public int CreateDepreciation(string XMLControlData, string CompanyIndex) {
            return base.Channel.CreateDepreciation(XMLControlData, CompanyIndex);
        }
        
        public int CreateProduct(string XMLControlData, string CompanyIndex) {
            return base.Channel.CreateProduct(XMLControlData, CompanyIndex);
        }
        
        public System.Data.DataTable GetDataTable_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex) {
            return base.Channel.GetDataTable_Search(objSearch, CompanyIndex);
        }
        
        public System.Data.DataTable GetDataTable(string strQuery, string CompanyIndex) {
            return base.Channel.GetDataTable(strQuery, CompanyIndex);
        }
        
        public System.Data.DataSet GetDataSet_Search(Microsoft.Windows.Controls.CommonService.SearchCriteria objSearch, string CompanyIndex) {
            return base.Channel.GetDataSet_Search(objSearch, CompanyIndex);
        }
    }
}
